using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel;

namespace Smiley.Lib.Enums
{
    public enum Sound
    {
        [Description("Sounds\\AbilityDeselect")]
        AbilityDeSelect,
        [Description("Sounds\\AbilitySelect")]
        AbilitySelect,
        [Description("Sounds\\AreaChangeDown")]
        AreaChangeDown,
        [Description("Sounds\\AreaChangeUp")]
        AreaChangeUp,
        [Description("Sounds\\BartletSpawn")]
        BartletSpan,
        [Description("Sounds\\BartliBreathing")]
        BartliBreathing,
        [Description("Sounds\\BartliHit1")]
        BartliHit1,
        [Description("Sounds\\BartliHit2")]
        BartliHit2,
        [Description("Sounds\\BartliHit3")]
        BartliHit3,
        [Description("Sounds\\BartliJumpLand")]
        BartliJumpLand,
        [Description("Sounds\\BartliRunning")]
        BartliRunning,
        [Description("Sounds\\ButtonClick")]
        ButtonClick,
        [Description("Sounds\\calypsoEvil")]
        CalypsoEvil,
        [Description("Sounds\\ChangeMenu")]
        ChangeMenu,
        [Description("Sounds\\ClockTick")]
        ClickTick,
        [Description("Sounds\\Construction")]
        Construction,
        [Description("Sounds\\CornwallisGroundSpike")]
        CornwallisGroundSpike,
        [Description("Sounds\\Crusher")]
        Crusher,
        [Description("Sounds\\DeShrink")]
        DeShrink,
        [Description("Sounds\\DoorUnlock")]
        DoorUnlock,
        [Description("Sounds\\drowning")]
        Drowning,
        [Description("Sounds\\EndTut")]
        EndTut,
        [Description("Sounds\\enemyDeath")]
        EnemyDeath,
        [Description("Sounds\\Error")]
        Error,
        [Description("Sounds\\explosion1")]
        Explosion1,
        [Description("Sounds\\explosion2")]
        Explosion2,
        [Description("Sounds\\explosion3")]
        Explosion3,
        [Description("Sounds\\Falling")]
        Falling,
        [Description("Sounds\\FenwarSlurp")]
        FenwarSlurp,
        [Description("Sounds\\firebossdie")]
        FireBossDie,
        [Description("Sounds\\firebosshit")]
        FireBossHit,
        [Description("Sounds\\firebossnova")]
        FireBossNova,
        [Description("Sounds\\FireBreath")]
        FireBreath,
        [Description("Sounds\\FireCannonLaunch")]
        FireCannonlaunch,
        [Description("Sounds\\FireBassBy")]
        FirePassBy,
        [Description("Sounds\\fireworm")]
        FireWorm,
        [Description("Sounds\\freeze")]
        Freeze,
        [Description("Sounds\\FrisbeeHitWall")]
        FrisbeeHitWall,
        [Description("Sounds\\garmbornRoar")]
        GarmbornRoar,
        [Description("Sounds\\gem")]
        Gem,
        [Description("Sounds\\gem3")]
        Gem3,
        [Description("Sounds\\Health")]
        Health,
        [Description("Sounds\\HintMan")]
        HintMan,
        [Description("Sounds\\Hit1")]
        Hit1,
        [Description("Sounds\\Hit2")]
        Hit2,
        [Description("Sounds\\Hit3")]
        Hit3,
        [Description("Sounds\\Hit4")]
        Hit4,
        [Description("Sounds\\Hit5")]
        Hit5,
        [Description("Sounds\\HitByFireball")]
        HitByFireball,
        [Description("Sounds\\HitInvulnerable")]
        HitInvulnerable,
        [Description("Sounds\\HitTut1")]
        HitTut1,
        [Description("Sounds\\HitTut2")]
        HitTut2,
        [Description("Sounds\\HopOntoIce")]
        HopOntoIce,
        [Description("Sounds\\Hopping")]
        Hopping,
        [Description("Sounds\\ice_die")]
        IceDie,
        [Description("Sounds\\icebreath")]
        IceBreath,
        [Description("Sounds\\Jesus")]
        Jesus,
        [Description("Sounds\\key")]
        Key,
        [Description("Sounds\\Lava")]
        Lava,
        [Description("Sounds\\Lick1")]
        Lick1,
        [Description("Sounds\\Lick2")]
        Lick2,
        [Description("Sounds\\Lick3")]
        Lick3,
        [Description("Sounds\\Lick4")]
        Lick4,
        [Description("Sounds\\Lick5")]
        Lick5,
        [Description("Sounds\\LightningOrb")]
        LightningOrb,
        [Description("Sounds\\LovecraftHit1")]
        LovecraftHit1,
        [Description("Sounds\\LovecraftHit2")]
        LovecraftHit2,
        [Description("Sounds\\LovecraftHit3")]
        LovecraftHit3,
        [Description("Sounds\\Mana")]
        Mana,
        [Description("Sounds\\MouseOver")]
        MouseOver,
        [Description("Sounds\\NewItem2")]
        NewItem2,
        [Description("Sounds\\penguinSplash")]
        PenguinSplash,
        [Description("Sounds\\purchaseUpgrade")]
        PurchaseUpgrade,
        [Description("Sounds\\ReflectionShield")]
        ReflectionShield,
        [Description("Sounds\\RumbleLoop")]
        RumbleLoop,
        [Description("Sounds\\ShallowWater")]
        ShallowWater,
        [Description("Sounds\\Shrink")]
        Shrink,
        [Description("Sounds\\sillypad")]
        SillyPad,
        [Description("Sounds\\SlimeSplat")]
        SlimeSplat,
        [Description("Sounds\\SnowFootstep")]
        SnowFootstep,
        [Description("Sounds\\splat")]
        Splat,
        [Description("Sounds\\StartTut")]
        StartTut,
        [Description("Sounds\\switch")]
        Switch,
        [Description("Sounds\\SwitchItem")]
        SwitchItem,
        [Description("Sounds\\TentaclesExtend")]
        TentaclesExtend,
        [Description("Sounds\\TextBoxChange")]
        TextBoxChange,
        [Description("Sounds\\tongue")]
        Tongue,
        [Description("Sounds\\treeletRoar")]
        TreeletRoar,
        [Description("Sounds\\TutCoffinOpen")]
        TutCoffinOpen,
        [Description("Sounds\\Warp")]
        Warp
    }
}
