using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Smiley.Lib.Enums
{
    public enum CollisionTile
    {
        NUM_COLLISION = 36,
        WALKABLE = 0,
        UNWALKABLE = 1,
        RED_KEYHOLE = 2,
        YELLOW_KEYHOLE = 3,
        GREEN_KEYHOLE = 4,
        BLUE_KEYHOLE = 5,
        EVIL_DOOR = 6,
        SHALLOW_WATER = 7,
        DEEP_WATER = 8,
        UP_ARROW = 9,
        RIGHT_ARROW = 10,
        DOWN_ARROW = 11,
        LEFT_ARROW = 12,
        SLIME = 13,
        SPRING_PAD = 14,
        FIRE_DESTROY = 15,
        WALK_LAVA = 16,
        NO_WALK_LAVA = 17,
        UNWALKABLE_PROJECTILE = 18,
        RED_WARP = 19,
        BLUE_WARP = 20,
        YELLOW_WARP = 21,
        GREEN_WARP = 22,
        SPIN_ARROW_SWITCH = 23,
        PIT = 24,
        FOUNTAIN = 25,
        SAVE_SHRINE = 26,
        SIGN = 27,
        ICE = 28,
        MIRROR_UP_LEFT = 29,
        MIRROR_UP_RIGHT = 30,
        MIRROR_DOWN_RIGHT = 31,
        MIRROR_DOWN_LEFT = 32,
        MIRROR_SWITCH = 33,
        ENEMY_NO_WALK = 34,
        GREEN_WATER = 35,
        DIZZY_MUSHROOM_1 = 36,
        DIZZY_MUSHROOM_2 = 37,
        BOMB_PAD_UP = 38,
        BOMB_PAD_DOWN = 39,
        BOMBABLE_WALL = 40,
        HOVER_PAD = 41,
        WHITE_CYLINDER_DOWN = 42,
        YELLOW_CYLINDER_DOWN = 43,
        GREEN_CYLINDER_DOWN = 44,
        BLUE_CYLINDER_DOWN = 45,
        BROWN_CYLINDER_DOWN = 46,
        SILVER_CYLINDER_DOWN = 47,
        SHRINK_TUNNEL_SWITCH = 48,
        SHRINK_TUNNEL_HORIZONTAL = 49,
        SHRINK_TUNNEL_VERTICAL = 50,
        SHALLOW_GREEN_WATER = 51,
        EVIL_WALL_POSITION = 52,
        EVIL_WALL_TRIGGER = 53,
        EVIL_WALL_DEACTIVATOR = 54,
        EVIL_WALL_RESTART = 55,
        FLAME = 56,
        SUPER_SPRING = 57,
        WHITE_CYLINDER_UP = 58,
        YELLOW_CYLINDER_UP = 59,
        GREEN_CYLINDER_UP = 60,
        BLUE_CYLINDER_UP = 61,
        BROWN_CYLINDER_UP = 62,
        SILVER_CYLINDER_UP = 63,
        SMILELET = 64,
        SMILELET_FLOWER_SAD = 65,
        SMILELET_FLOWER_HAPPY = 66,
        NO_WALK_PIT = 67,
        FAKE_PIT = 68,
        NO_WALK_WATER = 69,
        FAKE_COLLISION = 70,

        WHITE_SWITCH_LEFT = 74,
        YELLOW_SWITCH_LEFT = 75,
        GREEN_SWITCH_LEFT = 76,
        BLUE_SWITCH_LEFT = 77,
        BROWN_SWITCH_LEFT = 78,
        SILVER_SWITCH_LEFT = 79,

        WHITE_SWITCH_RIGHT = 90,
        YELLOW_SWITCH_RIGHT = 91,
        GREEN_SWITCH_RIGHT = 92,
        BLUE_SWITCH_RIGHT = 93,
        BROWN_SWITCH_RIGHT = 94,
        SILVER_SWITCH_RIGHT = 95,

        PLAYER_START = 224,
        PLAYER_END = 225
    }
}
